import { existsSync, mkdirSync, readdirSync, watch } from 'node:fs'
import { builtinModules } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import { $ } from 'bun'
import type { BunPlugin } from 'bun'

interface PackageJson {
	name: string
}

interface ManifestJson {
	id: string
}

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)))
const packageJson = (await Bun.file('package.json').json()) as PackageJson
const manifestJson = (await Bun.file('manifest.json').json()) as ManifestJson

export const SRC = 'src'
export const DIST = 'dist'
export const ASSETS_SRC = `${SRC}/assets`
export const STYLES_SRC = `${SRC}/styles.src.css`
export const STYLES_OUT = `${DIST}/styles.css`
export const PLUGIN_ID = manifestJson.id || packageJson.name
export const BANNER = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN.
If you want to view the source, please visit the github repository of this plugin.
*/
`

const excalidrawDistAliases = {
	'@excalidraw/common': resolve(rootDir, 'excalidraw/packages/common/dist/prod/index.js'),
	'@excalidraw/element': resolve(rootDir, 'excalidraw/packages/element/dist/prod/index.js'),
	'@excalidraw/fractional-indexing': resolve(
		rootDir,
		'excalidraw/packages/fractional-indexing/dist/prod/index.js'
	),
	'@excalidraw/math': resolve(rootDir, 'excalidraw/packages/math/dist/prod/index.js'),
	'@excalidraw/utils': resolve(rootDir, 'excalidraw/packages/utils/dist/prod/index.js')
}

const excalidrawDistAliasPlugin: BunPlugin = {
	name: 'excalidraw-dist-alias',
	setup(build) {
		for (const [specifier, path] of Object.entries(excalidrawDistAliases)) {
			build.onResolve(
				{ filter: new RegExp(`^${specifier.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) },
				() => ({
					path
				})
			)
		}
	}
}

export const EXTERNAL_MODULES = [
	'obsidian',
	'electron',
	'@excalidraw/excalidraw',
	'@codemirror/autocomplete',
	'@codemirror/collab',
	'@codemirror/commands',
	'@codemirror/language',
	'@codemirror/lint',
	'@codemirror/search',
	'@codemirror/state',
	'@codemirror/view',
	'@lezer/common',
	'@lezer/highlight',
	'@lezer/lr',
	...builtinModules
]

const { values } = parseArgs({
	args: Bun.argv,
	options: {
		prod: {
			type: 'boolean',
			default: false
		}
	},
	strict: true,
	allowPositionals: true
})
const isProd = values.prod

export function ensureDistDir(): void {
	if (!existsSync(DIST)) {
		mkdirSync(DIST, { recursive: true })
	}
}

async function buildStyles(): Promise<void> {
	console.log('Building CSS...')
	try {
		const minifyFlag = isProd ? '--minify' : ''
		await $`bunx @tailwindcss/cli -i ${STYLES_SRC} -o ${STYLES_OUT} ${minifyFlag}`.quiet()
		console.log('CSS build succeeded.')
	} catch (error) {
		console.error('CSS build failed:', error)
		if (isProd) {
			throw error
		}
	}
}

async function buildJs(): Promise<void> {
	console.log(`Building plugin in ${isProd ? 'production' : 'development'} mode...`)
	const { success, logs } = await Bun.build({
		banner: BANNER,
		entrypoints: [`${SRC}/main.ts`],
		outdir: DIST,
		external: EXTERNAL_MODULES,
		format: 'cjs',
		target: 'node',
		minify: isProd,
		sourcemap: isProd ? 'none' : 'inline',
		throw: isProd,
		plugins: [excalidrawDistAliasPlugin]
	})

	if (success) {
		console.log('JS build succeeded.')
	} else {
		console.error('JS build failed.')
		console.error(logs)
	}
}

async function copyAssets(): Promise<void> {
	console.log('Copying assets...')

	if (existsSync(ASSETS_SRC)) {
		const glob = new Bun.Glob('**/*')
		for await (const file of glob.scan({ cwd: ASSETS_SRC, onlyFiles: true })) {
			const src = join(ASSETS_SRC, file)
			const dest = join(DIST, file)
			await Bun.write(dest, Bun.file(src))
			console.log(`  ✓ ${file}`)
		}
	}

	await Bun.write(join(DIST, 'manifest.json'), Bun.file('manifest.json'))
	console.log('  ✓ manifest.json')
	await Bun.write(join(DIST, 'versions.json'), Bun.file('versions.json'))
	console.log('  ✓ versions.json')
}

async function copyToVault(): Promise<void> {
	const vaultPath = process.env['OBSIDIAN_VAULT_LOCATION']
	if (!vaultPath) {
		console.log(
			'Tip: Set OBSIDIAN_VAULT_LOCATION to auto-copy the plugin to your vault after each build.'
		)
		return
	}

	const pluginDir = join(vaultPath, '.obsidian', 'plugins', PLUGIN_ID)
	if (!existsSync(pluginDir)) {
		console.log(`Creating plugin directory: ${pluginDir}`)
		mkdirSync(pluginDir, { recursive: true })
	}

	console.log(`Copying dist to ${pluginDir}...`)
	for (const file of readdirSync(DIST)) {
		const src = join(DIST, file)
		const dest = join(pluginDir, file)
		await Bun.write(dest, Bun.file(src))
		console.log(`  ✓ ${file}`)
	}

	await Bun.write(join(pluginDir, '.hotreload'), '')
	console.log('  ✓ .hotreload')
}

async function build(): Promise<void> {
	ensureDistDir()
	await Promise.all([buildJs(), buildStyles(), copyAssets()])

	if (!isProd) {
		await copyToVault()
	}
}

if (import.meta.main) {
	await build()

	if (!isProd) {
		watch(SRC, { recursive: true }, async (event, path) => {
			console.log(`Detected ${event} in ${SRC}/${path}`)
			await build()
		})
	}
}
