import {
	SHIFT_LOCKING_ANGLE,
	DEFAULT_FONT_SIZE,
	DEFAULT_FONT_FAMILY,
	FONT_FAMILY,
	FONT_SIZES,
	MIN_FONT_SIZE,
	DEFAULT_TRANSFORM_HANDLE_SPACING,
	SIDE_RESIZING_THRESHOLD,
	TEXT_ALIGN,
	VERTICAL_ALIGN,
	DEFAULT_ELEMENT_PROPS,
	ROUGHNESS,
	STROKE_WIDTH,
	TOOL_TYPE,
	SVG_NS,
	COLOR_PALETTE,
	COLOR_OUTLINE_CONTRAST_THRESHOLD,
	DEFAULT_ELEMENT_STROKE_PICKS,
	DEFAULT_ELEMENT_BACKGROUND_PICKS,
	DEFAULT_COLLISION_THRESHOLD,
	getFontString,
	getFontFamilyString,
	getLineHeight,
	normalizeEOL,
	arrayToMap,
	randomId,
	isTransparent,
	isColorDark,
	rescalePoints
} from '@excalidraw/common'

import {
	newElement,
	newTextElement,
	newFreeDrawElement,
	newLinearElement,
	newArrowElement,
	mutateElement,
	newElementWith,
	bumpVersion,
	getElementAbsoluteCoords,
	getElementBounds,
	getCommonBoundingBox,
	getTransformHandles,
	getTransformHandlesFromCoords,
	DEFAULT_OMIT_SIDES,
	resizeSingleElement,
	resizeMultipleElements,
	getResizeOffsetXY,
	getResizeArrowDirection,
	getCursorForResizingElement,
	hitElementItself,
	hitElementBoundingBox,
	shouldTestInside,
	generateRoughOptions,
	ShapeCache,
	measureText,
	normalizeText,
	getLineHeightInPx,
	getMinTextElementWidth,
	getApproxMinLineWidth,
	getApproxMinLineHeight,
	wrapText,
	isLinearElementType,
	isBindableElement,
	isExcalidrawElement,
	hashString,
	Scene,
	LinearElementEditor
} from '@excalidraw/element'

import type {
	ExcalidrawElement,
	ExcalidrawGenericElement,
	ExcalidrawTextElement,
	ExcalidrawFreeDrawElement,
	ExcalidrawLinearElement,
	ExcalidrawArrowElement,
	ExcalidrawLineElement,
	NonDeletedExcalidrawElement,
	ElementsMap
} from '@excalidraw/element/types'

import type {
	TransformHandleType,
	TransformHandles,
	MaybeTransformHandleType
} from '@excalidraw/element/transformHandles'

import type { Zoom } from '@excalidraw/excalidraw/types'

import type { GlobalPoint } from '@excalidraw/math'

export {
	SHIFT_LOCKING_ANGLE,
	DEFAULT_FONT_SIZE,
	DEFAULT_FONT_FAMILY,
	FONT_FAMILY,
	FONT_SIZES,
	MIN_FONT_SIZE,
	DEFAULT_TRANSFORM_HANDLE_SPACING,
	SIDE_RESIZING_THRESHOLD,
	TEXT_ALIGN,
	VERTICAL_ALIGN,
	DEFAULT_ELEMENT_PROPS,
	ROUGHNESS,
	STROKE_WIDTH,
	TOOL_TYPE,
	SVG_NS,
	COLOR_PALETTE,
	COLOR_OUTLINE_CONTRAST_THRESHOLD,
	DEFAULT_ELEMENT_STROKE_PICKS,
	DEFAULT_ELEMENT_BACKGROUND_PICKS,
	DEFAULT_COLLISION_THRESHOLD,
	getFontString,
	getFontFamilyString,
	getLineHeight,
	normalizeEOL,
	arrayToMap,
	randomId,
	isTransparent,
	isColorDark,
	rescalePoints,
	newElement,
	newTextElement,
	newFreeDrawElement,
	newLinearElement,
	newArrowElement,
	mutateElement,
	newElementWith,
	bumpVersion,
	getElementAbsoluteCoords,
	getElementBounds,
	getCommonBoundingBox,
	getTransformHandles,
	getTransformHandlesFromCoords,
	DEFAULT_OMIT_SIDES,
	resizeSingleElement,
	resizeMultipleElements,
	getResizeOffsetXY,
	getResizeArrowDirection,
	getCursorForResizingElement,
	hitElementItself,
	hitElementBoundingBox,
	shouldTestInside,
	generateRoughOptions,
	ShapeCache,
	measureText,
	normalizeText,
	getLineHeightInPx,
	getMinTextElementWidth,
	getApproxMinLineWidth,
	getApproxMinLineHeight,
	wrapText,
	isLinearElementType,
	isBindableElement,
	isExcalidrawElement,
	hashString,
	Scene,
	LinearElementEditor
}

export type {
	ExcalidrawElement,
	ExcalidrawGenericElement,
	ExcalidrawTextElement,
	ExcalidrawFreeDrawElement,
	ExcalidrawLinearElement,
	ExcalidrawArrowElement,
	ExcalidrawLineElement,
	NonDeletedExcalidrawElement,
	ElementsMap,
	TransformHandleType,
	TransformHandles,
	MaybeTransformHandleType,
	Zoom,
	GlobalPoint
}

/** Fixed zoom for Annotation (1:1, no infinite canvas). */
export const ANNOTATION_ZOOM: Zoom = { value: 1 as number & { _brand: 'normalizedZoom' } }
